CREATE TABLE IF NOT EXISTS measurement_unit (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);


CREATE TABLE IF NOT EXISTS nomenclature_group (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);


CREATE TABLE IF NOT EXISTS nomenclature (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS organization (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredient (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe_step (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS storage_address (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS storage(
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS tbs (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS storage_transaction(
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS storage_turnover(
    id SERIAL PRIMARY KEY,
    uid VARCHAR(255) NOT NULL UNIQUE,
    data JSONB NOT NULL
);

