swagger: '2.0'
info:
  description: Bunch of services for Romashka company
  version: "1.0.0"
  title: RestAPI
produces:
  - application/json
  - application/xml
  - text/plain
basePath: "/api"
paths:
  /reports/formats:
    get:
      summary: Returns a list of supported report formats
      operationId: main.get_formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Internal server error
        default:
          description: Unexpected error
